config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :artists
  resources :groups

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :artists

	def calculate_avg_age()

	end

	def calculate_avg_height()

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		respond_to do |format|
			format.json { @artists = Artist.all }
			format.html { @artists = Artist.all }
		end
	end

	def show
		respond_to do |format|
			format.json { @artist = Artist.find(params[:id]) }
			format.html { @artist = Artist.find(params[:id]) }
		end
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)
		if @artist.save
			redirect_to @artist
		else
			render 'new'
		end
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def update
		@artist = Artist.find(params[:id])
		if @artist.update_attributes(artist_params)
			redirect_to @artist
		else
			render 'edit'
		end
	end

	def destroy
		@artist = Artist.find(params[:id])
		if @artist.destroy
			redirect_to artists_path
		else
			render 'show'
		end
	end

	private
		def artist_params
			params.require(:artist).permit(:first_name, :stage_name, :last_name, :agency, :isActor, :gender, :debut, :birthday, :bloodType, :horoscope, :image_url)
		end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def index
		respond_to do |format|
			format.json { @groups = Group.all }
			format.html { @groups = Group.all }
		end
	end

	def show
		respond_to do |format|
			format.json { @group = Group.find(params[:id]) }
			format.html { @group = Group.find(params[:id]) }
		end
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			@group.calculate_avg_age()
			@group.calculate_avg_height()
			redirect_to @group
		else
			render 'new'
		end
	end

	def edit
		@group = Group.find(params[:id])
	end

	def update
		@group = Group.find(params[:id])
		if @group.update_attributes(group_params)
			@group.calculate_avg_age()
			@group.calculate_avg_height()
			redirect_to @group
		else
			render 'edit'
		end
	end

	def destroy
		@group = Group.find(params[:id])
		if @group.destroy
			redirect_to groups_path
		else
			render 'show'
		end
	end

	private
		def group_params
			params.require(:group).permit(:image_url, :name, :agency, :num_members, :gender, :debut)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@groups = Group.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
	<div><%= f.label :first_name %>:</div>
	<div><%= f.text_field :first_name %></div>
	<div><%= f.label :stage_name %>:</div>
	<div><%= f.text_field :stage_name %></div>
	<div><%= f.label :last_name %>:</div>
	<div><%= f.text_field :last_name %></div>
	<div><%= f.label :agency %>:</div>
	<div><%= f.text_field :agency %></div>
	<div><%= f.label :isActor %>:</div>
	<div><%= f.check_box :isActor %></div>
	<div><%= f.label :gender %>:</div>
	<div><%= f.select :gender, %w{Male Female}, :include_blank => true %></div>
	<div><%= f.label :debut %>:</div>
	<div><%= f.date_select :debut, :order => [:month, :day, :year], :start_year => 1950 %></div>
	<div><%= f.label :birthday %>:</div>
	<div><%= f.date_select :birthday, :order => [:month, :day, :year], :start_year => 1950 %></div>
	<div><%= f.label :bloodType %>:</div>
	<div><%= f.select :bloodType, %w{A B AB O}, :include_blank => true %></div>
	<div><%= f.label :horoscope %>:</div>
	<div><%= f.select :horoscope, %w{Aries Taurus Gemini Cancer Leo Virgo Libra Scorpio Sagittarius Capricorn Aquarius Pisces}, :include_blank => true %></div>
	<div><%= f.label :image_url %>:</div>
	<div><%= f.text_field :image_url %></div>
	<br/>
	<div><%= f.submit %></div>
	<%= link_to "Back", artists_path %>
<% end %>

app/views/artists/index.html.erb
<h2> Artists </h2>

<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<table class="table table-hover" width="100%"> 
		<thead>
			<tr>
				<th>Profile Picture</th>
				<th>First Name</th>
				<th>Stage Name</th>
				<th>Last Name</th>
				<th>Agency</th>
				<th>Actor?</th>
				<th>Gender</th>
				<th>Debut Date</th>
				<th>Birthday</th>
				<th>Blood Type</th>
				<th>Zodiac Sign</th>
				<th colspan="11"></th>
			</tr>
		</thead>

		<tbody>
			<% @artists.each do |artist| %>
				<tr>
					<td><img width="100px" src=<%= artist.image_url%>></img></td>
					<td><%= artist.first_name %></td>
					<td><%= artist.stage_name %></td>
					<td><%= artist.last_name %></td>
					<td><%= artist.agency %></td>
					<td><%= artist.isActor %></td>
					<td><%= artist.gender %></td>
					<td><%= artist.debut %></td>
					<td><%= artist.birthday %></td>
					<td><%= artist.bloodType %></td>
					<td><%= artist.horoscope %></td>
					<td><%= link_to 'Show', artist %></td>
					<td><%= link_to 'Edit', edit_artist_path(artist) %></td>
					<td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to 'Add New Artist', new_artist_path %>

app/views/artists/show.html.erb
<h2><%= @artist.last_name %></h2>
<h2><%= @artist.first_name %></h2>
<p> Stage Name: <%= @artist.stage_name %></p>

<img width="150px" src=<%= @artist.image_url%>></img>
<p>
Agency: <%= @artist.agency %><br/>
Gender: <%= @artist.gender %><br/>
Birthday: <%= Date::MONTHNAMES[@artist.birthday.month] %> <%= @artist.birthday.day %>, <%= @artist.birthday.year %><br/>
Blood Type: <%= @artist.bloodType %><br/>
Zodiac Sign: <%= @artist.horoscope %><br/>
</p>
<br/>

<p><%= link_to "Edit", edit_artist_path %></p>
<p><%= link_to "Back", artists_path %></p>
<p><%= link_to "Delete", @artist, method: "delete" %></p>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
	<div><%= f.label :name %>:</div>
	<div><%= f.text_field :name %></div>
	<div><%= f.label :agency %>:</div>
	<div><%= f.text_field :agency %></div>
	<div><%= f.label :num_members %>:</div>
	<div><%= f.number_field :num_members %></div>
	<div><%= f.label :gender %>:</div>
	<div><%= f.select :gender, %w{Male Female}, :include_blank => true %></div>
	<div><%= f.label :debut %>:</div>
	<div><%= f.date_select :debut, :order => [:month, :day, :year], :start_year => 1950 %></div>
	<div><%= f.label :image_url %>:</div>
	<div><%= f.text_field :image_url %></div>
	<br/>
	<div><%= f.submit %></div>
	<%= link_to "Back", groups_path %>
<% end %>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<h2> Groups </h2>

<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<table class="table table-hover" width="100%"> 
		<thead>
			<tr>
				<th>Picture</th>
				<th>Group Name</th>
				<th>Agency</th>
				<th>Number of Members</th>
				<th>Gender</th>
				<th>Debut Date</th>
				<th>Average Age</th>
				<th>Average Height</th>
				<th colspan="8"></th>
			</tr>
		</thead>

		<tbody>
			<% @groups.each do |group| %>
				<tr>
					<td><img width="150px" src=<%= group.image_url%>></img></td>
					<td><%= group.name %></td>
					<td><%= group.agency %></td>
					<td><%= group.num_members %></td>
					<td><%= group.gender %></td>
					<td><%= group.debut %></td>
					<td><%= group.avg_age %></td>
					<td><%= group.avg_height %></td>
					<td><%= link_to 'Show', group %></td>
					<td><%= link_to 'Edit', edit_group_path(group) %></td>
					<td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to 'Add New Group', new_group_path %>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<h2><%= @group.name %></h2>

<img width="150px" src=<%= @group.image_url%>></img>
<p>
Agency: <%= @group.agency %><br/>
Gender: <%= @group.gender %><br/>
Debut Date: <%= Date::MONTHNAMES[@group.debut.month] %> <%= @group.debut.day %>, <%= @group.debut.year %><br/>
Average Age: <%= @group.avg_age %><br/>
Average Height: <%= @group.avg_height %><br/>
</p>
<br/>

<p><%= link_to "Edit", edit_group_path %></p>
<p><%= link_to "Back", groups_path %></p>
<p><%= link_to "Delete", @group, method: "delete" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>All About Kpop</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<!-- Body -->
<body>
	<!-- Wrap -->
	<div id="wrap">	
		<!-- <div class="container"> -->
		<!-- Navbar -->
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <!-- <a class="navbar-brand" href="#">All About Kpop</a> -->
		      <%= link_to "All About Kpop", root_path, :class => 'navbar-brand' %>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><%= link_to "Groups", groups_path, :class => 'active' %></li>
		        <li><%= link_to "Artists", artists_path %></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		            <li class="divider"></li>
		            <li><a href="#">One more separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		      <form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		<!-- End Navbar -->

		<%= yield %>
		<!-- </div> -->
		<div id="push"></div>
	</div>
	<!-- End Wrap -->

	<!-- Footer -->
    <div id="footer">
      <div class="container">
        <p class="muted credit">Footer</p>
      </div>
    </div>
    <!-- End Footer -->

</body>
<!-- End Body -->

</html>

app/views/welcome/index.html.erb
<% @groups.each do |group| %>
	<img width="300px" src=<%= group.image_url %>></img>
<% end %>